finds stores based on actual route time
Team9353/food-deserts pull request #121
Opened 2020-04-12 09:03 UTC by hannahli23

Changes
----

- Changed app.js back for easy to test purposes
- Changed map.js to return stores to the frontend based on actual route's time

Screenshots
----
![image](https://user-images.githubusercontent.com/19498941/79064939-c6f77700-7c61-11ea-9b6f-2a96f4656996.png)

- 

Resolved issues
-----

Closes #

2020-04-12 15:32 UTC, evan10s requested changes
I haven't tested it, but undoing most of the changes in server/app.js should get it building again in CI

2020-04-12 15:32 UTC, evan10s commented on package.json
> +    "google-distance-matrix": "^1.1.1"
This should be a server dependency

2020-04-12 15:32 UTC, evan10s commented on server/app.js
> +app.set("view engine", "jade");
This should be ejs

2020-04-12 15:32 UTC, evan10s commented on server/app.js
> -app.use("/api/v1/map", mapRouter);
All the routing changes in this file should be reverted so the frontend is server properly

2020-04-14 02:54 UTC, 9353oasis commented
<!--
  2 failure:  Files in the [`cl..., Files in the [`se...
  0 warning: 
  2 messages
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Files in the [`client`](/client) directory were modified; please update the client version.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Files in the [`server`](/server) directory were modified; please update the server version.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  
<tr>
      <td>ℹ</td>
      <td>This pull request includes server dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a4636a4f1e08e7b9b21e5cee88fdec35ef3bafb2
</p>

2020-04-14 03:06 UTC, 9353oasis commented
<!--
  0 failure: 
  0 warning: 
  2 messages
  
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes server dependency changes.</td>
    </tr>
  
<tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 58d376a63155d3edd7db91da1266b13b278e32d7
</p>

2020-04-14 03:09 UTC, evan10s approved these changes

2020-04-14 03:10 UTC, 9353oasis commented
<!--
  0 failure: 
  0 warning: 
  2 messages
  
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes server dependency changes.</td>
    </tr>
  
<tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f8506828383ca393f7add46fadac0b94db06cfb3
</p>

2020-04-14 21:06 UTC, merged