Home page 13
Team9353/food-deserts pull request #35
Opened 2020-01-22 05:06 UTC by hannahli23

- Created an Accordion Styled drop down 
- Added a Navlink to lead to the maps page
- Added the semantic-ui-react stylesheet

2020-01-22 16:41 UTC, oamyette3 submitted a review, later dismissed

2020-01-22 16:41 UTC, oamyette3 commented on client/src/index.js
> +
Put css in a different file and link!!

2020-01-22 16:43 UTC, evan10s requested changes

2020-01-22 16:43 UTC, evan10s commented on client/package.json
> +    "semantic-ui-react": "latest"
Probably shouldn't target `latest` version of a dependency, for consistency reasons.  You can put in the specific version you need

2020-01-23 22:39 UTC, evan10s commented
Please also increment the version in client/package.json since you modified files there

2020-01-24 03:33 UTC, evan10s requested changes
Fix the package.json dependency set to "latest" and remove the raw Javascript to add CSS

2020-01-24 04:43 UTC, evan10s approved these changes
lgtm

2020-01-24 04:46 UTC, merged