Functional Google Maps autocomplete
Team9353/food-deserts pull request #80
Opened 2020-03-04 08:25 UTC by evan10s

Changes
----

- Got Google Maps autocomplete functionality working on a basic level

In #76, we will actually link this autocomplete with the rest of the UI, but for now the component will return the lat/long for the location selected, even if that isn't displayed in the UI.  The other UI complexities as part of #2 will also be address with #76.

Screenshots
----

- 
![image (8)](https://user-images.githubusercontent.com/5790137/75859213-96e9c800-5dc7-11ea-90a7-b3400708c4cd.png)

Resolved issues
-----

Closes #2

2020-03-04 08:26 UTC, 9353oasis commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a5dc341ca2e9b32c462a9f442a0f598a79cc903f
</p>

2020-03-05 02:32 UTC, hannahli23 commented on client/src/components/MapContainer.js
> +import {GoogleMap, Marker, withGoogleMap, withScriptjs} from "react-google-maps"
Semicolon here!

2020-03-05 02:33 UTC, hannahli23 commented on client/src/components/MapContainer.js
> +            style={{minHeight: "400px", height: "500px", maxHeight: "100px", minWidth: '500px', maxWidth: "800px"}}/>,
your minWidth needs to be in double quotes

2020-03-05 02:33 UTC, hannahli23 commented on client/src/components/MapContainer.js
> +        mapElement: <div style={{height: '100%'}}/>,
same here, double quotes

2020-03-05 02:34 UTC, hannahli23 commented on client/src/components/map/AutocompleteV2.js
> +import React from 'react';
For this entire file, replace single with double quotes

2020-03-05 02:35 UTC, hannahli23 commented on client/src/components/map/GmAutocomplete.js
> +        }
Semicolon here apparently

2020-03-05 02:36 UTC, hannahli23 requested changes
I reviewed the code and it looked fine, so I ended up just making some codacy comments

2020-03-06 05:03 UTC, 9353oasis commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>ℹ</td>
      <td>This pull request includes client dependency changes.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9bb9da69119f7cfe4bd5fb319d57be6c95be43c7
</p>

2020-03-26 04:58 UTC, evan10s commented
I'm gonna close this for now and re-open as a wizard PR once that feature is done

2020-03-26 04:58 UTC, closed without merging